# Generated by Django 5.1.2 on 2024-11-15 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_page', '0003_reviewbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Укажите имя заказчика')),
                ('phone_number', models.IntegerField(verbose_name='Укажите ваш номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Уажите вашу почту')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.library')),
            ],
        ),
    ]
